---
- include: epel7.yml

- copy:
    dest: /etc/yum.repos.d/walters-buildtools.repo
    content: |
      [walters-buildtools]
      name=Copr repo for buildtools owned by walters
      baseurl=https://copr-be.cloud.fedoraproject.org/results/walters/buildtools/epel-7-$basearch/
      gpgcheck=1
      gpgkey=https://copr-be.cloud.fedoraproject.org/results/walters/buildtools/pubkey.gpg
      enabled=1
      enabled_metadata=1

- copy:
    dest: /etc/yum.repos.d/centos7-atomic.repo
    content: |
      [centos7-atomic]
      name=CentOS7 Atomic
      baseurl=http://buildlogs.centos.org/centos/7/atomic/x86_64/Packages/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      enabled=1
      enabled_metadata=1

# Ensure we see fresh data
- command: yum clean expire-cache      

# COPR is down right now
- command: yum -y install https://s3.amazonaws.com/cdn.verbum.org/rpmdistro-gitoverlay-2016.2.8.gd053af7-1.el7.noarch.rpm

- yum: name={{ item }} state=present
  with_items:
    - rsync
    - mock
    - rpm-ostree
    - fedpkg
    - rpmdistro-gitoverlay

# nspawn is better, also https://lists.fedoraproject.org/pipermail/buildsys/2015-July/004833.html
# Also https://bugzilla.redhat.com/show_bug.cgi?id=1328212
- lineinfile: dest=/etc/mock/site-defaults.cfg line="config_opts['use_nspawn'] = True"

- user: name=builder groups=mock,wheel

- lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"

- authorized_key:
    user: builder
    key: "{{ lookup('file', lookup('env', 'WORKSPACE') + '/builder.key.pub') }}"
