---
- include: epel7.yml

- copy:
    dest: /etc/yum.repos.d/walters-buildtools.repo
    content: |
      [walters-buildtools]
      name=Copr repo for buildtools owned by walters
      baseurl=https://copr-be.cloud.fedoraproject.org/results/walters/buildtools/epel-7-$basearch/
      skip_if_unavailable=True
      gpgcheck=1
      gpgkey=https://copr-be.cloud.fedoraproject.org/results/walters/buildtools/pubkey.gpg
      enabled=1
      enabled_metadata=1

# Ensure we see fresh data
- command: yum clean expire-cache      

- yum: name={{ item }} state=present
  with_items:
    - rsync
    - mock
    - fedpkg
    - rpmdistro-gitoverlay

# nspawn is better, also https://lists.fedoraproject.org/pipermail/buildsys/2015-July/004833.html
# Also https://bugzilla.redhat.com/show_bug.cgi?id=1328212
- lineinfile: dest=/etc/mock/site-defaults.cfg line="config_opts['use_nspawn'] = True"

- user: name=builder groups=mock,wheel

- lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"

- authorized_key:
    user: builder
    key: "{{ lookup('file', lookup('env', 'WORKSPACE') + '/builder.key.pub') }}"
